# Dialog utility color scheme White:

_dialog_scheme_files()
{
	echo 'aspect = 0
	separate_widget = ""
	tab_len = 0
	visit_items = OFF
	use_shadow = ON
	use_colors = ON
	screen_color = (CYAN,BLUE,ON)
	shadow_color = (BLACK,BLACK,ON)
	dialog_color = (BLACK,WHITE,OFF)
	title_color = (BLUE,WHITE,ON)
	border_color = (WHITE,WHITE,ON)
	button_active_color = (WHITE,BLUE,ON)
	button_inactive_color = dialog_color
	button_key_active_color = button_active_color
	button_key_inactive_color = (RED,WHITE,OFF)
	button_label_active_color = (YELLOW,BLUE,ON)
	button_label_inactive_color = (BLACK,WHITE,ON)
	inputbox_color = dialog_color
	inputbox_border_color = dialog_color
	searchbox_color = dialog_color
	searchbox_title_color = title_color
	searchbox_border_color = border_color
	position_indicator_color = title_color
	menubox_color = dialog_color
	menubox_border_color = border_color
	item_color = dialog_color
	item_selected_color = button_active_color
	tag_color = title_color
	tag_selected_color = button_label_active_color
	tag_key_color = button_key_inactive_color
	tag_key_selected_color = (WHITE,BLUE,ON)
	check_color = dialog_color
	check_selected_color = button_active_color
	uarrow_color = (GREEN,WHITE,ON)
	darrow_color = uarrow_color
	itemhelp_color = (WHITE,BLACK,OFF)
	form_active_text_color = button_active_color
	form_text_color = (WHITE,CYAN,ON)
	form_item_readonly_color = (CYAN,WHITE,ON)
	gauge_color = title_color
	border2_color = dialog_color
	inputbox_border2_color = dialog_color
	searchbox_border2_color = dialog_color
	menubox_border2_color = dialog_color' > "$HOME/kfn/dialog_color_scheme_default_custom"

	# Dialog utility color scheme Black+Blue:

	echo 'aspect = 0
	separate_widget = ""
	tab_len = 0
	visit_items = OFF
	use_shadow = OFF
	use_colors = ON
	screen_color = (CYAN,BLUE,ON)
	shadow_color = (WHITE,WHITE,ON)
	dialog_color = (WHITE,BLACK,OFF)
	title_color = (BLUE,BLACK,ON)
	border_color = (WHITE,BLACK,ON)
	button_active_color = (BLUE,BLUE,ON)
	button_inactive_color = (WHITE,BLACK,ON)
	button_key_active_color = button_active_color
	button_key_inactive_color = (BLUE,BLACK,ON)
	button_label_active_color = (WHITE,BLUE,ON)
	button_label_inactive_color = (WHITE,BLACK,ON)
	inputbox_color = (WHITE,BLACK,ON)
	inputbox_border_color = (WHITE,BLACK,ON)
	searchbox_color = (WHITE,BLACK,ON)
	searchbox_title_color = (WHITE,BLACK,ON)
	searchbox_border_color = (WHITE,BLACK,ON)
	position_indicator_color = title_color
	menubox_color = (WHITE,BLACK,ON)
	menubox_border_color = (WHITE,BLACK,ON)
	item_color = dialog_color
	item_selected_color = (WHITE,BLUE,ON)
	tag_color = (BLUE,BLACK,ON)
	tag_selected_color = button_label_active_color
	tag_key_color = button_key_inactive_color
	tag_key_selected_color = (CYAN,BLUE,ON)
	check_color = dialog_color
	check_selected_color = button_active_color
	uarrow_color = (GREEN,WHITE,ON)
	darrow_color = uarrow_color
	itemhelp_color = (WHITE,BLACK,OFF)
	form_active_text_color = button_active_color
	form_text_color = (WHITE,CYAN,ON)
	form_item_readonly_color = (CYAN,WHITE,ON)
	gauge_color = title_color
	border2_color = (WHITE,BLACK,ON)
	inputbox_border2_color = (WHITE,BLACK,ON)
	searchbox_border2_color = (WHITE,BLACK,ON)
	menubox_border2_color = (WHITE,BLACK,ON)' > "$HOME/kfn/dialog_color_scheme_black_and_blue"

	# Dialog utility color scheme Black+Green:

	echo 'aspect = 0
	separate_widget = ""
	tab_len = 0
	visit_items = OFF
	use_shadow = OFF
	use_colors = ON
	screen_color = (CYAN,BLUE,ON)
	shadow_color = (WHITE,WHITE,ON)
	dialog_color = (WHITE,BLACK,OFF)
	title_color = (GREEN,BLACK,ON)
	border_color = (WHITE,BLACK,ON)
	button_active_color = (GREEN,GREEN,ON)
	button_inactive_color = (WHITE,BLACK,ON)
	button_key_active_color = button_active_color
	button_key_inactive_color = (GREEN,BLACK,ON)
	button_label_active_color = (WHITE,GREEN,ON)
	button_label_inactive_color = (WHITE,BLACK,ON)
	inputbox_color = (WHITE,BLACK,ON)
	inputbox_border_color = (WHITE,BLACK,ON)
	searchbox_color = (WHITE,BLACK,ON)
	searchbox_title_color = (WHITE,BLACK,ON)
	searchbox_border_color = (WHITE,BLACK,ON)
	position_indicator_color = title_color
	menubox_color = (WHITE,BLACK,ON)
	menubox_border_color = (WHITE,BLACK,ON)
	item_color = dialog_color
	item_selected_color = (WHITE,GREEN,ON)
	tag_color = (GREEN,BLACK,ON)
	tag_selected_color = button_label_active_color
	tag_key_color = button_key_inactive_color
	tag_key_selected_color = (WHITE,GREEN,ON)
	check_color = dialog_color
	check_selected_color = button_active_color
	uarrow_color = (GREEN,WHITE,ON)
	darrow_color = uarrow_color
	itemhelp_color = (WHITE,BLACK,OFF)
	form_active_text_color = button_active_color
	form_text_color = (WHITE,CYAN,ON)
	form_item_readonly_color = (CYAN,WHITE,ON)
	gauge_color = title_color
	border2_color = (WHITE,BLACK,ON)
	inputbox_border2_color = (WHITE,BLACK,ON)
	searchbox_border2_color = (WHITE,BLACK,ON)
	menubox_border2_color = (WHITE,BLACK,ON)' > "$HOME/kfn/dialog_color_scheme_black_and_green"
}
